### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Zumbalamambo** [Hortensie/AI_Trader#1]
Im getting the following error  while trying to build the app

`Error:A problem occurred configuring project ':app'.`

Im using android studio v2.3.3

**Comment by Hortensie** [comment]
Hello, I assume you are trying to build develop branch? If yes please make sure you have installed (all API between 21 -> 25 + NDK/Cmake + latest build versions). If it doesn't help sent me a screenshot from your studio at szczesny.piotr@outlook.com

**Comment by Hortensie** [comment]
I actually noticed that my last git hub code was not supporting Android Studio 2.3.3. I just committed those build dependencies to develop branch. Please get latest code & re -try.

**Comment by Zumbalamambo** [comment]
Thanks now im able to build. I guess the development is in the half way

**Comment by Hortensie** [comment]
You welcome. Well generally yes however there are some features that are working but UI needs to be improved to reflect and use some functionality.
